# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(blank=True, default=b'', max_length=100)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
                ('frames', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('frames',),
            },
        ),
    ]
