# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160606_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='replay',
            name='duration',
            field=models.PositiveSmallIntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='replay',
            name='frames',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
    ]
