# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160606_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='file',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
