# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_replay_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='audio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='replay',
            name='file',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
