# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160607_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='file',
            new_name='filePath',
        ),
    ]
