# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, default='', max_length=100)),
                ('row', models.CharField(blank=True, default='0', max_length=100)),
                ('col', models.CharField(blank=True, default='0', max_length=100)),
                ('sizeX', models.CharField(blank=True, default='1', max_length=100)),
                ('sizeY', models.CharField(blank=True, default='1', max_length=100)),
                ('order', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('case_key', models.CharField(blank=True, default='', max_length=100)),
                ('activity_en', models.CharField(blank=True, default='', max_length=100)),
                ('eventtime_table', models.CharField(blank=True, default='', max_length=100)),
                ('eventtime', models.CharField(blank=True, default='', max_length=100)),
                ('sorting', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('user_type', models.CharField(blank=True, default='', max_length=100)),
                ('tables_needed', models.CharField(blank=True, default='', max_length=100)),
                ('filter_needed', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
