# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160520_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ('process', 'name')},
        ),
        migrations.AddField(
            model_name='analysis',
            name='process',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
