# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160520_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='analysis',
            field=models.ManyToManyField(to='api.Analysis'),
        ),
    ]
