# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activity_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='analysis',
        ),
        migrations.AddField(
            model_name='activity',
            name='analysis',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
