# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160521_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='analysis',
        ),
        migrations.AddField(
            model_name='activity',
            name='analysis',
            field=models.ManyToManyField(to='api.Analysis'),
        ),
    ]
