# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160521_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='analysis',
        ),
        migrations.AddField(
            model_name='activity',
            name='analysis',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=1000),
        ),
    ]
