# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_activity_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='analysis',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=1000),
        ),
    ]
