# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_activity_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('process', models.CharField(blank=True, default=b'', max_length=100)),
            ],
            options={
                'ordering': ('process', 'name'),
            },
        ),
    ]
