# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tables_needed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='process',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
