# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160523_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tables_needed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
