# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160523_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
