# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activtiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Table')),
            ],
            options={
                'ordering': ('activtiy', 'table'),
            },
        ),
    ]
