# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_tableactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableactivity',
            options={},
        ),
        migrations.RemoveField(
            model_name='tableactivity',
            name='activtiy',
        ),
        migrations.AddField(
            model_name='tableactivity',
            name='activtiy',
            field=models.ManyToManyField(to='api.Activity'),
        ),
        migrations.RemoveField(
            model_name='tableactivity',
            name='table',
        ),
        migrations.AddField(
            model_name='tableactivity',
            name='table',
            field=models.ManyToManyField(to='api.Table'),
        ),
    ]
