# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160530_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableactivity',
            name='activtiy',
        ),
        migrations.RemoveField(
            model_name='tableactivity',
            name='table',
        ),
        migrations.AddField(
            model_name='activity',
            name='tables_required',
            field=models.ManyToManyField(blank=True, to='api.Table'),
        ),
        migrations.AddField(
            model_name='table',
            name='linked_activity',
            field=models.ManyToManyField(blank=True, to='api.Activity'),
        ),
        migrations.DeleteModel(
            name='TableActivity',
        ),
    ]
