# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_table_linked_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tables_required',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tables_needed',
        ),
        migrations.AddField(
            model_name='activity',
            name='tables_needed',
            field=models.ManyToManyField(blank=True, to='api.Table'),
        ),
    ]
