# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20160530_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tables_required',
            field=models.ManyToManyField(blank=True, to='api.Table'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tables_needed',
        ),
        migrations.AddField(
            model_name='activity',
            name='tables_needed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
