# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_activity_happy2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='happy2',
        ),
    ]
