# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_activity_tables_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.CharField(blank=True, default='System', max_length=4000),
        ),
    ]
