# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_activity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sql',
            field=models.CharField(blank=True, default='', max_length=8000),
        ),
    ]
